### ISSUE TITLE
Give brief site explanation

### ISSUE THREAD

**Issue by maya** [codeforamerica/court.atlantaga.gov#4]
To me it feels weird to have the FAQ nav link highlighted when I first visit the home page. Even though I understand you are showing the FAQ content on the home. What was your thinking about this?

**Comment by techieshark** [comment]
What if instead of FAQ it said 'Home / FAQ' or just 'Home'? I think it is alright as just FAQ actually (but it should be user tested by someone who doesn't already understand how it works).

**Comment by samhashemi** [comment]
Agree that the site needs a brief explanation of why you're here. Will add that soon.
