### ISSUE TITLE
Use one h1 per content section

### ISSUE THREAD

**Issue by maya** [codeforamerica/court.atlantaga.gov#5]
Looking at the home page...
It's recommended to have only one h1 tag per content section in HTML5: 
http://webdesign.tutsplus.com/articles/the-truth-about-multiple-h1-tags-in-the-html5-era--webdesign-16824

You can also wrap those with sections and keep them as is with multiple h1's.

**Comment by samhashemi** [comment]
The H1 tags are generated from Markdown by Jekyll, not styled by hand.
